listen: "0.0.0.0:2205"
mysql:
  server: "0.0.0.0:3306"
  password: "mysql"
sqlite:
  filePath: "internal/database/my_dtcg.db"
moecard:
  username: ""
  password: ""
  retry: 2 # 向 DtcgDB 服务器发送请求时的重试次数
jhs:
  username: ""
