listen: ":2205"
mysql:
  server: ""
  password: ""
sqlite:
  filePath: "internal/database/my_dtcg.db"
dtcgDB:
  username: ""
  password: ""
  token: ""
  retry: 2 # 向 DtcgDB 服务器发送请求时的重试次数
jhs:
  token: ""
